### ISSUE TITLE
AnsibleUndefinedVariable: 'unicode object' has no attribute 'options'

### ISSUE THREAD

**Issue by kenytux** [ISU-Ansible/ansible-autofs#10]
I've got this error and I can't solve it!
```
TASK [ansible-autofs : Create map-files] ******************************************************************************************************************
failed: [m2m_appli_1] (item={'value': {u'path': u'/nfs', u'options': [u'ghost', u'timeout=30']}, 'key': u'nfs'}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "nfs", "value": {"options": ["ghost", "timeout=30"], "path": "/nfs"}}, "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'options'"}
```

Here my variables
```
use_autofs_mounts: true
nfs_source: 32-hes1pdata01
autofs_mounts:
  Mount1:
    mount: "/var/sharedFolder/scape/taskResults"
    share: "{{ nfs_source }}:/var/sharedServer/scape/Aggregated"
    type: nfs
    options:
      - uid=2004
      - gid=3001
autofs_mounts_enabled:
  - Mount1

autofs_maps:
  nfs: 
    path: /nfs
    options: 
      - ghost
      - timeout=30
```
